name: Deploy to EC2

on:
  workflow_dispatch:   # 先手動觸發（安全）

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AWS EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker stop myapi || true
            sudo docker rm myapi || true
            sudo docker pull h8a2n5k23/myapi:latest
            sudo docker run -d --name myapi -p 8000:8000 h8a2n5k23/myapi:latest
