name: Deploy to local Kubernetes

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-k8s:
    runs-on: self-hosted

    steps:
      - name: Check kubectl context
        shell: cmd
        run: |
          kubectl config current-context
          kubectl get nodes

      - name: Restart deployment
        shell: cmd
        run: |
          kubectl apply -f deployment.yaml
          kubectl rollout restart deployment myapi-deployment
          kubectl rollout status deployment/myapi-deployment --timeout=60s